[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/my-account"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/refund"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
